### ISSUE TITLE
lnk_min/max precision

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#102]
The lnk_min/max currently look like this by default:

![image](https://user-images.githubusercontent.com/1272030/112692366-0f408280-8e3c-11eb-8ca1-06c1ea937f67.png)

We don't need allll the decimal places, just a couple.

**Comment by aneuhold** [comment]
Should this show all the decimal places if the user enters a lot, or should it only ever show 2 decimal places because of precision?

**Comment by steven-murray** [comment]
To be honest, this should actually be shown as a range slider, and yeah, really only need two decimal places of precision.
