### ISSUE TITLE
Design Idea: Collapsible Model Parameter Forms

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#104]
Some of the models have a LOT of parameters, including some of the default models (eg. Tinker for the HMF). This makes the vertical spacing quite long, and makes it easy to miss some of the inputs. One way around this might be to have the model parameter sections, that appear on the right of the model choices, as collapsible. Not sure if this is easy or hard. If easy, I'd say it's worth it.

At the moment, at the very least, the mass range and mass resolution are very easy to miss (being after all the Tinker parameters), and should be fixed. One way would be just to bring them to the top of the HMF section (so, above the choice for Tinker). Another would be to bring all the "resolution" kinds of parameters -- so lnk-range, mass-range, resolution, scale range, etc., into one section called "Ranges", which should be towards the top.

**Comment by aneuhold** [comment]
@steven-murray was this still wanted? Please see [this deploy for a possible implementation](https://60777947b87c5167c9b99400--thehalomod.netlify.app/). It can be reverted though.

**Comment by steven-murray** [comment]
Hmmmm. I almost like it. It has a few things that are not ideal -- like when there are no parameters, it still shows the grey horizontal separator. I feel like it should maybe only collapse if there are more than say 3 parameters? Not sure if this is possible. Also, I think I like having the parameters show to the right of the main dropdown for each model (then again, not sure this'd work with the collapsing). The reason for this is that in the future I'd like to stick a Latex equation below each model, which would fit neatly to the left of the parameter list (if there is one).

Thoughts?

**Comment by aneuhold** [comment]
@steven-murray alright! Those ideas were implemented. Check out the [deploy here](https://607a44ee3d12824b75f48a85--thehalomod.netlify.app/), or the screenshots below:

![image](https://user-images.githubusercontent.com/17774559/115098975-faf61f80-9ee7-11eb-8ca1-11aea1af3d95.png)
![image](https://user-images.githubusercontent.com/17774559/115099007-2842cd80-9ee8-11eb-8c16-11e2aae96bda.png)

**Comment by steven-murray** [comment]
Truly spectacular!
