### ISSUE TITLE
Parameter Names

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#105]
Some comments about parameter names:

* Under Halo Model: "Scale (log10)" should be "Real-Space Scale Range (log10 Mpc/h)"
* Under Halo Model: "Wavenumner (log10)" should be "Fourier Scale Range (log10 h/Mpc)"
* Number of r bins should be "Number of Real-Space Scales"
* Parameters like M_min and M_1 in the HOD section should have subscripts for the "min" and "1" if possible.
* greek names like "alpha" "beta" and "gamma" can be their unicode greek letters, if possible (α, β, etc)

**Comment by aneuhold** [comment]
@steven-murray could you please take a look at [this deploy](https://60764486bf4c38301e4026fa--thehalomod.netlify.app/) when you have some time to see if this is what you had in mind for this issue?

**Comment by steven-murray** [comment]
Thanks @aneuhold. Yes, all the comments I made have been corrected. However I noticed the following:

* The x-axis label on the plot is now on top rather than the bottom?
* lnk_min/lnk_max should be a range slider (and name changed to lnk range)
* extrapolate_with_eh should be "Extrapolate with EH?"

**Comment by aneuhold** [comment]
@steven-murray the x-axis label is on the top? Could you send a screenshot? Seeing the below on this end:
![image](https://user-images.githubusercontent.com/17774559/114785883-26370e00-9d32-11eb-8520-3bf061ea418f.png)
It has been in this orientation for quite some time, so not sure if what is meant is the label or the dropdown. 

Also, working on the other two requests 😄

**Comment by aneuhold** [comment]
Okay the second two requests have been fixed now as well. Just the question about the axis position is left.

**Comment by steven-murray** [comment]
It's doing it for all plot choices.

**Comment by aneuhold** [comment]
This one is tough because it doesn't seem to happen on any of my devices. Windows or Mac. I don't have a linux machine to test it on though. @Tengelma can you try out [this deploy](https://607a4a69bd520153494dccac--thehalomod.netlify.app/) and see if it makes the x-axis go to the top?
