### ISSUE TITLE
Add "Acknowledging" page

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#114]
There's a page to this effect on the current website. This should be added as a button in top-right.

**Comment by aneuhold** [comment]
@steven-murray Is that this section of the about page?

![image](https://user-images.githubusercontent.com/17774559/113233335-da756680-9253-11eb-9af0-19a7a3974513.png)

Or is it somewhere else?

**Comment by steven-murray** [comment]
Ah, yes it is. I forgot it wasn't it's own page any more. Can we make it it's own page though? I want to make it as easy as possible for people to cite the tool :-)

**Comment by aneuhold** [comment]
Yes no problem. Will start working on this 😄

**Comment by aneuhold** [comment]
@steven-murray how does this look?

![image](https://user-images.githubusercontent.com/17774559/113372639-00ffd400-931e-11eb-8a1f-9e575536c914.png)

Anything that should be changed? Navbar, navbar button name, navbar order, more content, etc.

**Comment by steven-murray** [comment]
Thanks @aneuhold. This looks good. Maybe change the navbar button name (and
page title) to "Acknowledge". There will be extra text eventually, once we
get #132 done. Perhaps in the meantime we should make the text the
following:

```
If you use TheHaloMod in your published research, please cite Murray et al.
(2020) <https://arxiv.org/abs/2009.14066>. If you used TheHaloMod primarily
for the halo mass functions (or you got here by searching for HMFcalc),
please also cite Murray et al. (2013) <http://arxiv.org/abs/1306.6721>.

Also, don't forget to cite the original papers of the models you used!

One more thing. If you find TheHaloMod to be a useful tool, help us out by
starring the git repository, and let us know what you're using it for! This
helps to justify development in the future!
```

The starring should obviously be linked, and the "let us know" should link
to a Github Discussion I think. That can be put in later.

**Comment by aneuhold** [comment]
@steven-murray should the `git repository` section of text be linked to HaloMod or TheHaloMod-SPA? If it is for TheHaloMod-SPA, we can setup a discussion now 😁 . Otherwise, ya, you would need to setup a discussion link for that one and send it our way.

**Comment by aneuhold** [comment]
This is what it looks like without the 3rd paragraph linking so far:

![image](https://user-images.githubusercontent.com/17774559/113437850-3fd46f00-939c-11eb-9ff3-3558b6a79878.png)

**Comment by steven-murray** [comment]
I think the end goal would be to push the -SPA repo into the main
thehalomod repo, so there's just one (I have no interest in maintaining the
old code once this is deployed!). I *could* just make a Discussion on the
standard repo now, and we can point it there already, I guess!

**Comment by aneuhold** [comment]
Okay, that makes sense. It might have some issues though if we were to do that because of the github secrets and URLs all pointing to the Github repo for `TheHaloMod-SPA`. It is something we could work through, but it would take some time.

**Comment by steven-murray** [comment]
Hmm. Maybe we should just leave it here then!

**Comment by steven-murray** [comment]
So, you could link here: https://github.com/halomod/TheHaloMod-SPA/discussions/new?category=Show-and-tell for the "let us know what you're using it for".

**Comment by aneuhold** [comment]
Beautiful. Adding it now 😄
