### ISSUE TITLE
Colors of plot lines

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#120]
The big issue here is that the color palette for the plot lines is too visually compact. There are too many greens that are close together in color-space, and I can't easily distinguish models. This should be fixed.

Of secondary importance: it might be nice if the user could choose the color of the lines. Perhaps by clicking on the legend somewhere, or perhaps in the Model box.

**Comment by aneuhold** [comment]
Finite set of colors (category 10) then wrap back around with dotted lines, etc.
