### ISSUE TITLE
Version of hmf/halomod shown on top

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#136]
Currently the version of hmf/halomod show in the top bar. I like this.

**Comment by aneuhold** [comment]
@steven-murray In an attempt to keep the toolbar clean, it was added as a tooltip to the about button. But not sure if that looks good. What do you think about where it should be placed? See [this deploy](https://60779002d7bcf0009b12df1e--thehalomod.netlify.app/) for what it looks like at the moment and the screenshot below:

![image](https://user-images.githubusercontent.com/17774559/114805089-38777300-9d57-11eb-9b2c-ad9d3861e1e1.png)

**Comment by steven-murray** [comment]
I think this looks good, actually. The only downside is of course that it's not obvious that the info is there until you mouse-over. I wonder if we could leave it like this, but also add their versions to the text on the about page?

**Comment by aneuhold** [comment]
@steven-murray How does this look? 

![image](https://user-images.githubusercontent.com/17774559/114947940-dd9b5580-9e02-11eb-937c-59fb5c594270.png)

**Comment by steven-murray** [comment]
Fantastic!
