### ISSUE TITLE
"Happy to hear from you" should point somewhere

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#142]
On the About page, the comment "happy to hear from you" screams out for a link so they can actually say something somewhere. Problem is, I'm not sure what the best place is. But I think actually a Conversation thread on the github repo might be the ideal place. I can create such a thread, and point people there.

**Comment by aneuhold** [comment]
Link was added to the "show and tell discussion". Does this work? Or maybe a different discussion?

![image](https://user-images.githubusercontent.com/17774559/113459342-15010f80-93ca-11eb-8e20-f45be775f912.png)

**Comment by steven-murray** [comment]
@aneuhold I presume it's the link I mentioned previously (i.e. starts a new discussion in the "Show and Tell" Category?

**Comment by aneuhold** [comment]
Yes sir.

**Comment by aneuhold** [comment]
https://6069e18f6a5bb42385809788--thehalomod.netlify.app/acknowledge

**Comment by aneuhold** [comment]
Just wanted to check back in and see if this issue is satisfied by the current deployment? [dev.thehalomod.app](https://dev.thehalomod.app/)

**Comment by steven-murray** [comment]
Yup, perfect!
