### ISSUE TITLE
Server Readme Comments

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#91]
Some comments I thought about when reading the server readme:

* In the installation section, it might be useful to point out whether the user must create/enter a virtual environment before running `./run.sh --install`. It's very common for Python types to manage their envs through `conda` or `poetry`, and to enter it manually before installing anything.
* It occurred to me -- you're using the `requirements.txt` to pin dependencies. Are you using a specific system to update those dependencies? It's quite difficult to get consistent pinned deps with just `pip`.
* When running `redis-server` I get `174707:M 19 Mar 2021 11:09:16.143 # Could not create server TCP listening socket *:6379: bind: Address already in use`. I figure this was fine, probably set it up to run automatically previously. But, then when I ran `. ./run.sh --test` I got:

```
================================================================== short test summary info ===================================================================
FAILED tests/test_halomod.py::test_get_plot_data - TypeError: argument of type 'NoneType' is not iterable
FAILED tests/test_halomod.py::test_plot - redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able t...
FAILED tests/test_halomod.py::test_create - redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able...
```

This might be something I'm doing wrong, but if so, the docs should be updated. Otherwise, there's a bug in the code :-)

* When starting the server, I get the warning "Some Halo-Exclusion models have significant speedup when using Numba", indicating that numba is not in the requirements. This should be added -- it really does make some things faster!

**Comment by aschnapp** [comment]
@steven-murray for ```bind: Address already in use``` you'll need to kill the process that's currently running on port 6379 then run ```redis-server``` again. 
This is how you do it on a unix machine
https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux/32592965
The python issue should resolve itself after you have redis running.

**Comment by steven-murray** [comment]
Thanks @aschnapp, I'll give that a whirl.

**Comment by steven-murray** [comment]
It seems that the easiest way to do this was just `redis-cli shutdown` then `redis-server` again. Not sure if that means I just should have left it running in the first place (perhaps I have it running as a service).

**Comment by aschnapp** [comment]
Yeah that's another way to do it. You could have just started the server and not shut down and restart redis and it'll work too.
