### ISSUE TITLE
Client Readme Comments

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#92]
* I can't seem to install `serve` properly for local production runs. I've tried `npm i serve` and `yarn global add serve`. Both times, when running `serve dist -p 5111`, I get the error "command not found: serve". Am I doing something wrong?

Just in general, I expect that people working on this (essentially myself) will be *far less* familiar with JS/vue/node etc. than python. The docs here are great high-level stuff, and the function-level documentation in the files is great. I just wonder if there's something we can do between these levels. Perhaps what I'm looking for is just a tutorial on how to use vue, which I'm sure exists in abundance ;-)

**Comment by aneuhold** [comment]
You are absolutely right. Those things should be included. We should make a user story about updating the documentation in that way, or maybe just a quick PR. 

What should have been in the documentation for the client is probably running `npm install -g serve`. Can you try that out really quick and see if the `serve dist -p 5111` command works then?

**Comment by steven-murray** [comment]
Great, yeah that worked :-) I did have to run it as `sudo` though.

**Comment by aneuhold** [comment]
A user story was added for this as well. 🚀
