### ISSUE TITLE
Little Usability Improvements

### ISSUE THREAD

**Issue by aneuhold** [halomod/TheHaloMod-SPA#95]
It might be nice to have some little usability improvements. Priority and the contents of this US can be discussed with Steven. @steven-murray if you wanted to check some of these out and put in your thoughts if you have some time that would be helpful 🙂 .

- The model name isn’t centered to the icons on the right <img width="300" src="https://user-images.githubusercontent.com/17774559/111856310-07865880-88e7-11eb-9a19-300ec1c28e4c.png">
- It might be nice to have a ? icon next to things like “Models“, “Download“, and “Plot“ which has a little popup that explains what is is for. 
- It also might be nice to have the title at the top left link back to the home page. 
- The about page could include a link to the Github page for the project.
- “Submit issue“ could be added to the top bar kind of like with the original website.
- If the plot remembered what was last selected, it might be more intuitive for the user when they return to the main page.
- If the plot defaulted to an axis combo that wasn’t a straight line  😛 
![image](https://user-images.githubusercontent.com/17774559/111856289-e02f8b80-88e6-11eb-893a-e61d31c6c7cc.png)

**Comment by vperuzzi** [comment]
I agree with these improvements. I was going to suggest that we add some minor enhancements to some of the UI components that you mentioned here. Thank you for creating this US!
